---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
     app: myapp
spec: 
  replicas: 3
  selector: 
   matchLables: 
     app: myapp 
  template: 
    metadata:
     labels:
       app: myapp
     spec:  
       containers:
       - name: my-container
         image: nginx:2.2.1
         ports:
         - containerport:8080    

