---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
     app: myapp 
     version: 2.6.1
spec:
   type: NodePort
   ports:    
   - port: 8080
     nodeport:  30001
     protocol: TCP
   selector:
       app: myapp
       version: 2.6.1